### ISSUE TITLE
Feature request ? sudo apt install ros-humble-clearpath-desktop does not install  ros-humble-clearpath-common

### ISSUE THREAD

**Issue by y2d2** [clearpathrobotics/clearpath_desktop#8]
Hi,
 
**System setup**
_Running in a docker:_ 
Ubuntu: 22.04 
ROS Distro: Humble 

**Issue** 
When following the documentation `https://docs.clearpathrobotics.com/docs/ros/installation/remote_pc` it seems only the  ros-humble-clearpath-desktop has to be installed however running`ros2 run clearpath_generator_common generate_bash -s ~/clearpath`
returns `Package 'clearpath_generator_common' not found`. 
 
running `sudo apt-get install ros-humble-clearpath-common`  and retry solved the issue. 

**Solution**
Possibly adding:
` <exec_depend>clearpath_generator_common</exec_depend>`
into the file `clearpath_desktop/clearpath_desktop/package.xml` could solve this, but I am not sure if this is enough for the apt-get install command. 

Cheers,

**Comment by hilary-luo** [comment]
I believe that this has already been addressed, so you can either build this repo from source or wait for the update to be released in the debian package.
